---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels  # change accordingly
    volumes:
      - /path/to/nextcloud/config:/config
      - /path/to/nextcloud/data:/data
    ports:
      - 4443:443
    restart: always