---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
    - PUID=1000
    - GUID=1000
    - TZ=Europe/Brussels  # change accordingly
    - WEBUI_PORT=8080
    - TORRENTING_PORT=6881
  ports:
    - 8080:8080
    - 6881:6881
    - 6881:6881/udp
  volumes:
    - /path/to/bittorrent/appdata:/config
    - /path/to/bittorrent/downloads:/downloads
  restart: always